
# Site settings

title: JWO2018k # kurssitoteutuksen tunnus
baseurl: "/jwo2018k"

kurssin_nimi: Johdatus web-ohjelmointiin
kurssin_ajankohta: "Kevät 2018"

discussion_address: "https://moodle2.tut.fi/mod/forum/discuss.php?d="
upload_address: "https://moodle2.tut.fi/mod/vpl/view.php?id="

# review_address: "https://moodle2.tut.fi/mod/url/view.php?id=314337"
review_address: "https://moodle2.tut.fi/mod/url/view.php?id=361246"


# Build settings

markdown: kramdown

collections:

  osa1:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 1
    otsikko: "Selainpään perustekniikoista I - HTML, CSS"
    julkaisu: 5.1.2018

  osa2:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 2
    otsikko: "Selainpään perustekniikoista II - CSS, JavaScript"
    julkaisu: 12.1.2018

  osa3:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 3
    otsikko: "Selainpään kirjastoista - jQuery, Bootstrap"
    julkaisu: 19.1.2018

  osa4:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 4
    otsikko: "Palvelinpään ohjelmoinnista - Node, Express, Handlebars"
    julkaisu: 26.1.2018

  osa5:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 5
    otsikko: "Tietokannan käsittelystä - SQLite"
    julkaisu: 2.2.2018

  osa6:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 6
    otsikko: "Soveltavia tehtäviä I"
    julkaisu: 9.2.2018

  osa7:
    output: true
    permalink: /:collection/:path/
    nimi: Osa 7
    otsikko: "Soveltavia tehtäviä II"
    julkaisu: 16.2.2018
